"""
tests/test_seismic_tools.py
----------------------------
Pytest tests for seismic tools (tools 2, 6, 7).

These tests run against the synthetic SEG-Y file generated by
generate_synthetic_data.py.  Run `python generate_synthetic_data.py` once
before running pytest.
"""

from __future__ import annotations

import os
import sys
import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from tools import (
    list_seismic_surveys,
    get_seismic_survey_info,
    get_seismic_amplitude_stats,
)

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def data_dir() -> str:
    return os.path.join(os.path.dirname(__file__), "..", "data")


@pytest.fixture(scope="module")
def surveys(data_dir: str):
    return list_seismic_surveys(data_dir)


@pytest.fixture(scope="module")
def apex_path(surveys) -> str:
    for s in surveys:
        if "apex" in s["survey_name"].lower() or "apex" in s["filename"].lower():
            return s["filename"]
    pytest.fail("Survey-Apex not found — did you run generate_synthetic_data.py?")


@pytest.fixture(scope="module")
def survey_info(apex_path: str) -> dict:
    return get_seismic_survey_info(apex_path)


# ---------------------------------------------------------------------------
# Test 1: list_seismic_surveys
# ---------------------------------------------------------------------------

class TestListSeismicSurveys:
    def test_finds_apex_survey(self, surveys):
        assert len(surveys) >= 1
        names = [s["survey_name"].lower() + s["filename"].lower() for s in surveys]
        assert any("apex" in n for n in names), "Survey-Apex not found"

    def test_filenames_are_real(self, surveys):
        for s in surveys:
            assert os.path.isfile(s["filename"]), f"Missing: {s['filename']}"

    def test_missing_dir_raises(self):
        with pytest.raises(FileNotFoundError):
            list_seismic_surveys("/no/such/path")


# ---------------------------------------------------------------------------
# Test 2: get_seismic_survey_info
# ---------------------------------------------------------------------------

class TestGetSeismicSurveyInfo:
    def test_inline_range(self, survey_info):
        assert survey_info["inline_min"] == 100
        assert survey_info["inline_max"] == 120

    def test_crossline_range(self, survey_info):
        assert survey_info["crossline_min"] == 50
        assert survey_info["crossline_max"] == 70

    def test_sample_count(self, survey_info):
        assert survey_info["n_samples_per_trace"] == 500

    def test_sample_interval_ms(self, survey_info):
        assert abs(survey_info["sample_interval_ms"] - 2.0) < 0.01

    def test_total_time_ms(self, survey_info):
        # 500 samples × 2 ms = 1000 ms
        assert abs(survey_info["total_time_ms"] - 1000.0) < 1.0

    def test_result_keys(self, survey_info):
        for key in ("inline_min", "inline_max", "crossline_min", "crossline_max",
                    "n_traces", "n_samples_per_trace", "sample_interval_ms",
                    "total_time_ms"):
            assert key in survey_info

    def test_missing_file_raises(self):
        with pytest.raises(FileNotFoundError):
            get_seismic_survey_info("/no/such/survey.segy")


# ---------------------------------------------------------------------------
# Test 3: get_seismic_amplitude_stats
# ---------------------------------------------------------------------------

class TestGetSeismicAmplitudeStats:
    def test_valid_trace_returns_stats(self, apex_path):
        result = get_seismic_amplitude_stats(
            apex_path, inline=100, crossline=50,
            time_min_ms=0.0, time_max_ms=200.0
        )
        assert result["sample_count"] > 0
        assert result["mean_amplitude"] != 0.0
        for key in ("mean_amplitude", "min_amplitude", "max_amplitude", "rms_amplitude"):
            assert key in result

    def test_rms_is_non_negative(self, apex_path):
        result = get_seismic_amplitude_stats(
            apex_path, inline=110, crossline=60,
            time_min_ms=100.0, time_max_ms=500.0
        )
        assert result["rms_amplitude"] >= 0.0

    def test_min_leq_mean_leq_max(self, apex_path):
        result = get_seismic_amplitude_stats(
            apex_path, inline=115, crossline=65,
            time_min_ms=0.0, time_max_ms=400.0
        )
        assert result["min_amplitude"] <= result["mean_amplitude"] <= result["max_amplitude"]

    def test_invalid_inline_raises(self, apex_path):
        with pytest.raises(ValueError, match="not found"):
            get_seismic_amplitude_stats(
                apex_path, inline=999, crossline=50,
                time_min_ms=0.0, time_max_ms=200.0
            )

    def test_invalid_time_range_raises(self, apex_path):
        with pytest.raises(ValueError):
            get_seismic_amplitude_stats(
                apex_path, inline=100, crossline=50,
                time_min_ms=800.0, time_max_ms=400.0   # reversed — invalid
            )

    def test_time_exceeds_survey_raises(self, apex_path):
        with pytest.raises(ValueError):
            get_seismic_amplitude_stats(
                apex_path, inline=100, crossline=50,
                time_min_ms=0.0, time_max_ms=5000.0    # beyond 1000 ms
            )

    def test_different_inlines_give_different_means(self, apex_path):
        """Amplitude should vary between traces (not a constant field)."""
        r1 = get_seismic_amplitude_stats(apex_path, 100, 50, 0.0, 400.0)
        r2 = get_seismic_amplitude_stats(apex_path, 120, 70, 0.0, 400.0)
        # They won't be identical due to noise + frequency variation
        assert r1["mean_amplitude"] != r2["mean_amplitude"]
