"""
tests/test_well_tools.py
-------------------------
Pytest tests for well-log tools (tools 1, 3, 4, 5).

These tests run against the synthetic LAS files generated by
generate_synthetic_data.py.  Run `python generate_synthetic_data.py` once
before running pytest.
"""

from __future__ import annotations

import os
import sys
import pytest

# Make sure parent package is importable
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from tools import (
    list_wells,
    list_available_curves,
    get_curve_stats,
    flag_well_anomalies,
)

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def data_dir() -> str:
    return os.path.join(os.path.dirname(__file__), "..", "data")


@pytest.fixture(scope="module")
def wells(data_dir: str):
    return list_wells(data_dir)


@pytest.fixture(scope="module")
def well_alpha_path(wells) -> str:
    for w in wells:
        if "alpha" in w["well_name"].lower():
            return w["filename"]
    pytest.fail("Well-Alpha not found — did you run generate_synthetic_data.py?")


@pytest.fixture(scope="module")
def well_beta_path(wells) -> str:
    for w in wells:
        if "beta" in w["well_name"].lower():
            return w["filename"]
    pytest.fail("Well-Beta not found — did you run generate_synthetic_data.py?")


# ---------------------------------------------------------------------------
# Test 1: list_wells discovers both synthetic wells
# ---------------------------------------------------------------------------

class TestListWells:
    def test_returns_two_wells(self, wells):
        assert len(wells) >= 2, "Expected at least 2 LAS files"

    def test_well_names_present(self, wells):
        names = [w["well_name"].lower() for w in wells]
        assert any("alpha" in n for n in names), "Well-Alpha not found"
        assert any("beta" in n for n in names), "Well-Beta not found"

    def test_filenames_exist(self, wells):
        for w in wells:
            assert os.path.isfile(w["filename"]), f"File missing: {w['filename']}"

    def test_missing_dir_raises(self):
        with pytest.raises(FileNotFoundError):
            list_wells("/nonexistent/path/xyz")


# ---------------------------------------------------------------------------
# Test 2: list_available_curves
# ---------------------------------------------------------------------------

class TestListAvailableCurves:
    def test_alpha_has_expected_curves(self, well_alpha_path):
        curves = list_available_curves(well_alpha_path)
        curve_upper = [c.upper() for c in curves]
        for expected in ("DEPT", "GR", "NPHI", "RHOB", "RT"):
            assert expected in curve_upper, f"Missing curve: {expected}"

    def test_nonexistent_file_raises(self):
        with pytest.raises(FileNotFoundError):
            list_available_curves("/no/such/file.las")


# ---------------------------------------------------------------------------
# Test 3: get_curve_stats — Well-Alpha sandy zone
# ---------------------------------------------------------------------------

class TestGetCurveStats:
    def test_gr_stats_sandy_zone(self, well_alpha_path):
        """Well-Alpha's GR in the sandy zone (2000–2500 m) should average low (~20-50 GAPI)."""
        result = get_curve_stats(well_alpha_path, "GR", 2000.0, 2500.0)
        assert result["mean"] < 70, f"Expected low GR in sandy zone, got {result['mean']}"
        assert result["min"] >= 0
        assert result["count"] > 0

    def test_result_contains_required_keys(self, well_alpha_path):
        result = get_curve_stats(well_alpha_path, "NPHI", 2000.0, 2500.0)
        for key in ("well_file", "curve", "depth_min_m", "depth_max_m",
                    "count", "mean", "min", "max", "unit"):
            assert key in result, f"Missing key: {key}"

    def test_invalid_curve_raises(self, well_alpha_path):
        with pytest.raises(ValueError, match="not found"):
            get_curve_stats(well_alpha_path, "BADCURVE", 2000.0, 2500.0)

    def test_invalid_depth_range_raises(self, well_alpha_path):
        with pytest.raises(ValueError, match="must be less than"):
            get_curve_stats(well_alpha_path, "GR", 2500.0, 2000.0)

    def test_beta_rhob_carbonate_zone(self, well_beta_path):
        """Well-Beta is carbonate-dominated — RHOB should be > 2.55 on average."""
        result = get_curve_stats(well_beta_path, "RHOB", 2500.0, 3000.0)
        assert result["mean"] > 2.50, f"Carbonate RHOB too low: {result['mean']}"

    def test_beta_gr_shale_interbeds(self, well_beta_path):
        """Well-Beta shale interbeds (3000–3200 m) should show high GR."""
        result = get_curve_stats(well_beta_path, "GR", 3000.0, 3200.0)
        assert result["mean"] > 50, f"Expected high GR in shale interbeds: {result['mean']}"


# ---------------------------------------------------------------------------
# Test 4: flag_well_anomalies
# ---------------------------------------------------------------------------

class TestFlagWellAnomalies:
    def test_alpha_high_gr_shale(self, well_alpha_path):
        """Gamma ray > 70 should flag shale intervals above the reservoir."""
        intervals = flag_well_anomalies(well_alpha_path, "GR", threshold=70.0, above=True)
        assert len(intervals) > 0, "Expected some high-GR (shale) intervals"
        for iv in intervals:
            assert "depth_start_m" in iv and "depth_end_m" in iv

    def test_alpha_low_rt_shale(self, well_alpha_path):
        """Resistivity < 15 should flag shale (non-reservoir) intervals."""
        intervals = flag_well_anomalies(well_alpha_path, "RT", threshold=15.0, above=False)
        assert len(intervals) > 0, "Expected some low-RT (shale) intervals"

    def test_beta_high_rt_carbonate(self, well_beta_path):
        """Carbonate RT > 100 Ohm·m should produce many intervals in Well-Beta."""
        intervals = flag_well_anomalies(well_beta_path, "RT", threshold=100.0, above=True)
        assert len(intervals) > 0

    def test_invalid_curve_raises(self, well_alpha_path):
        with pytest.raises(ValueError):
            flag_well_anomalies(well_alpha_path, "GHOST", 50.0)
